// Product overlay on top of the evidence base (emissions.json). Input of
// scripts/build-catalogue.mjs, which writes src/data/catalogue/*.ts from the two.
// One row per catalogue action. Evidence rows keep their evidence id; rows with `xpOnly: true`
// have no evidence and therefore carry no CO2e claim.
//
// Fields
//   cat        product category: move | eat | power | water | stuff | waste | nature
//   emoji, title  UI tile
//   def        default preset (must be one of the evidence presets, or of `presets` when overridden)
//   presets    override of the evidence presets (optional)
//   cap        hard daily unit cap (optional override of evidence ux.suggestedDailyCap)
//   xp         XP per rewarded act
//   acts       'unit' -> every whole unit is one act (meals, loads, items)
//              'log'  -> one act per log entry whatever the quantity (km, minutes, kg, litres, days)
//              number -> one log is worth this many acts (diet days = 3 meals)
//   maxActs    rewarded acts per day for this action
//   group      shared-cap group (see GROUPS)
//   cadence    'recurring' (annualised in the pace metric) | 'occasional' (summed over 365 days, never scaled)
//   credit     'log' (kg credited at log time) | 'context' (figure shown as context only, never added to totals)
//   cf         one-line counterfactual shown in the sheet
//
// GROUPS cap rewarded acts per day across their member actions. `hint` is the one honest
// line the log sheet shows; `unitCap` is a combined hard cap on quantity where the spec has one.
export const GROUPS = {
  plate: { label: 'One tile per meal', maxActs: 3, hint: 'One tile per meal — pick the best fit.' },
  'food-rescue': {
    label: 'Same food, one tile',
    maxActs: 2,
    hint: 'Same food, one tile: by weight or by meal.',
  },
  laundry: {
    label: 'One temperature per load',
    maxActs: 2,
    hint: 'One temperature per load.',
    unitCap: 3,
  },
  'hot-water': { label: 'Same water, one tile', maxActs: 2, hint: 'Same water, one tile.' },
  recycling: {
    label: 'Sorting is one job',
    maxActs: 2,
    hint: 'Recycling a bottle and refusing one are alternatives for the same bottle.',
  },
  'single-use': { label: 'Small refusals', maxActs: 3, hint: null },
  'flight-swap': {
    label: 'One tile per trip',
    maxActs: 1,
    hint: "Use the flight's distance, not the rail distance.",
  },
  secondhand: { label: 'Second-hand finds', maxActs: 2, hint: 'Only if it replaced buying new.' },
  custom: { label: 'Custom actions', maxActs: 2, hint: null },
};

// Variant picked by default for actions whose evidence row carries labelled variants.
export const DEFAULT_VARIANTS = {
  'repair-instead-of-replace': 'small-appliance',
  'borrow-instead-of-buy': 'tool',
};

// Sheet notes the spec binds to single actions (section 3.3, "special handling").
export const NOTES = {
  'ebike-escooter-instead-of-car':
    'Shared scooters often replace walking — log those only if they replaced a car trip.',
  'thermostat-down-1c': 'Only on days the heating is on. Never below a healthy 18 °C.',
  'standby-off': 'One log per household, per day.',
  'led-bulb-swap':
    'Day one only is counted. Each bulb keeps saving a little every day it replaces an old incandescent.',
  'keep-phone-one-more-year': 'Counted once, over the coming year.',
  'plant-a-tree': "It's storage, not a cancelled emission, so we don't add it to your total.",
  'tap-off-while-brushing': 'Tiny for the climate, still a good habit.',
  'local-seasonal-swap': 'What you eat matters far more than where it came from.',
};

export const OVERLAY = [
  // ── Move ──────────────────────────────────────────────────────────────────
  {
    id: 'walk-cycle-instead-of-car',
    cat: 'move',
    emoji: '🚶',
    title: 'Walked or cycled instead of driving',
    def: 2,
    xp: 15,
    acts: 'log',
    maxActs: 2,
    cadence: 'recurring',
    cf: 'the same trip in an average car',
  },
  {
    id: 'bus-instead-of-car',
    cat: 'move',
    emoji: '🚌',
    title: 'Took the bus instead of driving',
    def: 5,
    xp: 12,
    acts: 'log',
    maxActs: 2,
    cadence: 'recurring',
    cf: 'driving it alone, minus the bus’s own emissions',
  },
  {
    id: 'train-metro-instead-of-car',
    cat: 'move',
    emoji: '🚆',
    title: 'Took the train or metro instead of driving',
    def: 10,
    xp: 12,
    acts: 'log',
    maxActs: 2,
    cadence: 'recurring',
    cf: 'driving it alone, minus the train’s own emissions',
  },
  {
    id: 'carpool',
    cat: 'move',
    emoji: '🚗',
    title: 'Shared the ride',
    def: 10,
    xp: 12,
    acts: 'log',
    maxActs: 2,
    cadence: 'recurring',
    cf: 'everyone driving alone; your share of the car-km avoided',
  },
  {
    id: 'ebike-escooter-instead-of-car',
    cat: 'move',
    emoji: '🛴',
    title: 'Rode my e-bike or e-scooter instead of driving',
    def: 5,
    xp: 12,
    acts: 'log',
    maxActs: 2,
    cadence: 'recurring',
    cf: 'the same trip in an average car, minus charging',
  },
  {
    id: 'ev-instead-of-petrol-car',
    cat: 'move',
    emoji: '🔌',
    title: 'Drove electric instead of petrol',
    def: 10,
    xp: 8,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'the same distance in an average petrol car, minus charging',
  },
  {
    id: 'work-from-home-day',
    cat: 'move',
    emoji: '🏠',
    title: 'Worked from home instead of commuting by car',
    def: 1,
    xp: 10,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'your car commute, minus the extra energy used at home',
  },
  {
    id: 'train-instead-of-short-flight-km',
    cat: 'move',
    emoji: '🚄',
    title: 'Took the train instead of a short flight',
    def: 500,
    xp: 40,
    acts: 'log',
    maxActs: 1,
    group: 'flight-swap',
    cadence: 'occasional',
    cf: 'an economy seat on a short-haul flight, minus the train',
  },
  {
    id: 'train-instead-of-short-flight-trip',
    cat: 'move',
    emoji: '🚄',
    title: 'Took the train instead of a short flight (distance unknown)',
    def: 1,
    xp: 40,
    acts: 'log',
    maxActs: 1,
    group: 'flight-swap',
    cadence: 'occasional',
    cf: 'a one-way short-haul flight of about 500 km, minus the train',
  },
  {
    id: 'car-free-day',
    xpOnly: true,
    cat: 'move',
    emoji: '🛑',
    title: 'Car-free day',
    unit: 'day',
    presets: [1],
    def: 1,
    cap: 1,
    xp: 10,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'not quantified: the kilograms come from the trips you log',
  },
  // ── Eat ───────────────────────────────────────────────────────────────────
  {
    id: 'plant-based-meal',
    cat: 'eat',
    emoji: '🌱',
    title: 'Plant-based meal',
    def: 1,
    xp: 15,
    acts: 'unit',
    maxActs: 3,
    group: 'plate',
    cadence: 'recurring',
    cf: 'a typical meal with meat',
  },
  {
    id: 'plant-based-instead-of-beef',
    cat: 'eat',
    emoji: '🫘',
    title: 'Plant-based instead of a beef meal',
    def: 1,
    xp: 15,
    acts: 'unit',
    maxActs: 3,
    group: 'plate',
    cadence: 'recurring',
    cf: 'the same meal made with about 100 g of beef',
  },
  {
    id: 'chicken-instead-of-beef',
    cat: 'eat',
    emoji: '🍗',
    title: 'Chicken instead of beef',
    def: 1,
    cap: 3,
    xp: 12,
    acts: 'unit',
    maxActs: 3,
    group: 'plate',
    cadence: 'recurring',
    cf: 'the same 100 g serving as beef',
  },
  {
    id: 'vegetarian-day',
    cat: 'eat',
    emoji: '🥗',
    title: 'Vegetarian day',
    def: 1,
    xp: 12,
    acts: 3,
    maxActs: 3,
    group: 'plate',
    cadence: 'recurring',
    cf: 'a day of typical meals with meat',
  },
  {
    id: 'vegan-day',
    cat: 'eat',
    emoji: '🌿',
    title: 'Fully plant-based day',
    def: 1,
    xp: 15,
    acts: 3,
    maxActs: 3,
    group: 'plate',
    cadence: 'recurring',
    cf: 'a day of typical meals with meat',
  },
  {
    id: 'plant-milk-instead-of-dairy',
    cat: 'eat',
    emoji: '🥛',
    title: 'Plant milk instead of dairy',
    def: 0.2,
    xp: 8,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'the same amount of cow’s milk',
  },
  {
    id: 'food-waste-avoided',
    cat: 'eat',
    emoji: '🥕',
    title: 'Saved food from the bin',
    def: 0.5,
    xp: 12,
    acts: 'log',
    maxActs: 2,
    group: 'food-rescue',
    cadence: 'recurring',
    cf: 'binning it and buying the same food again',
  },
  {
    id: 'meal-saved-from-waste',
    cat: 'eat',
    emoji: '🍲',
    title: 'Rescued a meal (leftovers, food-rescue app)',
    def: 1,
    xp: 12,
    acts: 'unit',
    maxActs: 2,
    group: 'food-rescue',
    cadence: 'recurring',
    cf: 'binning the meal and cooking another',
  },
  {
    id: 'local-seasonal-swap',
    cat: 'eat',
    emoji: '🧺',
    title: 'Chose local, seasonal produce',
    def: 1,
    xp: 8,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'the same meal with ingredients shipped the usual distances',
  },
  // ── Power ─────────────────────────────────────────────────────────────────
  {
    id: 'thermostat-down-1c',
    cat: 'power',
    emoji: '🌡️',
    title: 'Heating 1 °C lower',
    def: 1,
    xp: 15,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'the same home kept 1 °C warmer today',
  },
  {
    id: 'line-dry-instead-of-tumble',
    cat: 'power',
    emoji: '👕',
    title: 'Air-dried a load',
    def: 1,
    xp: 12,
    acts: 'unit',
    maxActs: 2,
    cadence: 'recurring',
    cf: 'the same load in a tumble dryer',
  },
  {
    id: 'standby-off',
    cat: 'power',
    emoji: '🔌',
    title: 'Switched standby devices off at the wall',
    def: 1,
    xp: 8,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'the household’s devices left on standby all day',
  },
  {
    id: 'led-bulb-swap',
    cat: 'power',
    emoji: '💡',
    title: 'Replaced an old bulb with an LED',
    def: 1,
    cap: 10,
    xp: 12,
    acts: 'log',
    maxActs: 1,
    cadence: 'occasional',
    cf: 'a 60 W bulb left in the fitting (day one only is counted)',
  },
  {
    id: 'ac-up-1c',
    xpOnly: true,
    cat: 'power',
    emoji: '🧊',
    title: 'AC 1 °C warmer, or a fan instead',
    unit: 'day',
    presets: [1],
    def: 1,
    cap: 1,
    xp: 12,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'not quantified: we have no sourced factor for cooling yet',
  },
  // ── Water ─────────────────────────────────────────────────────────────────
  {
    id: 'shorter-shower',
    cat: 'water',
    emoji: '🚿',
    title: 'Shorter shower',
    def: 2,
    xp: 12,
    acts: 'log',
    maxActs: 2,
    group: 'hot-water',
    cadence: 'recurring',
    cf: 'the same shower, that many minutes longer',
  },
  {
    id: 'hot-water-saved',
    cat: 'water',
    emoji: '🛁',
    title: 'Saved hot water',
    def: 10,
    xp: 10,
    acts: 'log',
    maxActs: 1,
    group: 'hot-water',
    cadence: 'recurring',
    cf: 'heating that many more litres',
  },
  {
    id: 'wash-30-instead-of-40',
    cat: 'water',
    emoji: '🫧',
    title: 'Washed at 30 °C instead of 40 °C',
    def: 1,
    xp: 10,
    acts: 'unit',
    maxActs: 2,
    group: 'laundry',
    cadence: 'recurring',
    cf: 'the same load at 40 °C',
  },
  {
    id: 'wash-cold-instead-of-40',
    cat: 'water',
    emoji: '❄️',
    title: 'Washed cold instead of 40 °C',
    def: 1,
    xp: 12,
    acts: 'unit',
    maxActs: 2,
    group: 'laundry',
    cadence: 'recurring',
    cf: 'the same load at 40 °C',
  },
  {
    id: 'tap-off-while-brushing',
    cat: 'water',
    emoji: '🪥',
    title: 'Tap off while brushing',
    def: 1,
    xp: 8,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'the tap left running, morning and evening',
  },
  // ── Stuff ─────────────────────────────────────────────────────────────────
  {
    id: 'second-hand-tshirt',
    cat: 'stuff',
    emoji: '👕',
    title: 'Bought a top second-hand',
    def: 1,
    xp: 18,
    acts: 'unit',
    maxActs: 2,
    group: 'secondhand',
    cadence: 'occasional',
    cf: 'the same garment bought new',
  },
  {
    id: 'second-hand-jeans',
    cat: 'stuff',
    emoji: '👖',
    title: 'Bought jeans second-hand',
    def: 1,
    xp: 18,
    acts: 'unit',
    maxActs: 2,
    group: 'secondhand',
    cadence: 'occasional',
    cf: 'the same jeans bought new',
  },
  {
    id: 'repair-instead-of-replace',
    cat: 'stuff',
    emoji: '🧵',
    title: 'Repaired instead of replacing',
    def: 1,
    xp: 20,
    acts: 'unit',
    maxActs: 2,
    cadence: 'occasional',
    cf: 'buying a new replacement',
  },
  {
    id: 'borrow-instead-of-buy',
    cat: 'stuff',
    emoji: '🤝',
    title: 'Borrowed or rented instead of buying',
    def: 1,
    xp: 15,
    acts: 'unit',
    maxActs: 2,
    cadence: 'occasional',
    cf: 'buying the item new',
  },
  {
    id: 'keep-phone-one-more-year',
    cat: 'stuff',
    emoji: '📱',
    title: 'Keeping my phone another year',
    def: 1,
    xp: 40,
    acts: 'log',
    maxActs: 1,
    cadence: 'occasional',
    cf: 'replacing it now with a new phone',
  },
  {
    id: 'pass-it-on',
    xpOnly: true,
    cat: 'stuff',
    emoji: '📦',
    title: 'Sold, donated or swapped something',
    unit: 'item',
    presets: [1, 3, 5],
    def: 1,
    cap: 10,
    xp: 12,
    acts: 'log',
    maxActs: 1,
    cadence: 'occasional',
    cf: 'not quantified: the saving belongs to whoever uses it next',
  },
  // ── Waste ─────────────────────────────────────────────────────────────────
  {
    id: 'recycle-aluminium-can',
    cat: 'waste',
    emoji: '🥫',
    title: 'Recycled aluminium cans',
    def: 2,
    xp: 10,
    acts: 'log',
    maxActs: 2,
    group: 'recycling',
    cadence: 'recurring',
    cf: 'landfill, and new cans made from ore',
  },
  {
    id: 'recycle-glass-bottle',
    cat: 'waste',
    emoji: '🫙',
    title: 'Recycled glass bottles or jars',
    def: 2,
    xp: 10,
    acts: 'log',
    maxActs: 2,
    group: 'recycling',
    cadence: 'recurring',
    cf: 'landfill, and new glass from raw materials',
  },
  {
    id: 'recycle-plastic-bottle',
    cat: 'waste',
    emoji: '🧴',
    title: 'Recycled plastic bottles',
    def: 2,
    xp: 10,
    acts: 'log',
    maxActs: 2,
    group: 'recycling',
    cadence: 'recurring',
    cf: 'landfill, and new plastic from oil',
  },
  {
    id: 'recycle-paper',
    cat: 'waste',
    emoji: '📰',
    title: 'Recycled paper or cardboard',
    def: 0.5,
    xp: 10,
    acts: 'log',
    maxActs: 2,
    group: 'recycling',
    cadence: 'recurring',
    cf: 'landfill, and new paper from virgin fibre',
  },
  {
    id: 'compost-food-waste',
    cat: 'waste',
    emoji: '🍂',
    title: 'Composted food scraps',
    def: 0.5,
    xp: 10,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'the same scraps rotting in landfill',
  },
  {
    id: 'refuse-single-use-bag',
    cat: 'waste',
    emoji: '🛍️',
    title: 'Brought my own bag',
    def: 1,
    xp: 8,
    acts: 'unit',
    maxActs: 3,
    group: 'single-use',
    cadence: 'recurring',
    cf: 'a single-use plastic carrier bag',
  },
  {
    id: 'refuse-single-use-cup',
    cat: 'waste',
    emoji: '☕',
    title: 'Used my own cup',
    def: 1,
    xp: 8,
    acts: 'unit',
    maxActs: 3,
    group: 'single-use',
    cadence: 'recurring',
    cf: 'a disposable cup',
  },
  {
    id: 'refuse-single-use-bottle',
    cat: 'waste',
    emoji: '🚰',
    title: 'Refilled my bottle',
    def: 1,
    xp: 8,
    acts: 'unit',
    maxActs: 3,
    group: 'single-use',
    cadence: 'recurring',
    cf: 'a 500 ml bottle of bought water',
  },
  {
    id: 'ewaste-dropoff',
    xpOnly: true,
    cat: 'waste',
    emoji: '🔋',
    title: 'Took e-waste or batteries to a collection point',
    unit: 'item',
    presets: [1, 3, 5],
    def: 1,
    cap: 20,
    xp: 15,
    acts: 'log',
    maxActs: 1,
    cadence: 'occasional',
    cf: 'not quantified: it prevents fires and recovers metals',
  },
  // ── Nature & Voice ────────────────────────────────────────────────────────
  {
    id: 'plant-a-tree',
    cat: 'nature',
    emoji: '🌳',
    title: 'Planted a tree',
    def: 1,
    xp: 20,
    acts: 'log',
    maxActs: 1,
    cadence: 'occasional',
    credit: 'context',
    cf: 'no tree; uptake is slow and only counts while the tree lives',
  },
  {
    id: 'litter-pick',
    cat: 'nature',
    emoji: '🧤',
    title: 'Picked up litter',
    def: 1,
    xp: 12,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'not quantified',
  },
  {
    id: 'habitat-volunteering',
    cat: 'nature',
    emoji: '🙌',
    title: 'Volunteered for nature',
    def: 1,
    xp: 25,
    acts: 'log',
    maxActs: 1,
    cadence: 'occasional',
    cf: 'not quantified',
  },
  {
    id: 'tend-plants',
    xpOnly: true,
    cat: 'nature',
    emoji: '🪴',
    title: 'Tended plants, garden or balcony',
    unit: 'session',
    presets: [1],
    def: 1,
    cap: 1,
    xp: 10,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'not quantified',
  },
  {
    id: 'help-wildlife',
    xpOnly: true,
    cat: 'nature',
    emoji: '🐝',
    title: 'Helped wildlife (feeder, bee hotel, a wild corner)',
    unit: 'session',
    presets: [1],
    def: 1,
    cap: 1,
    xp: 12,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'not quantified',
  },
  {
    id: 'climate-conversation',
    xpOnly: true,
    cat: 'nature',
    emoji: '💬',
    title: 'Had a real conversation about climate',
    unit: 'conversation',
    presets: [1],
    def: 1,
    cap: 2,
    xp: 15,
    acts: 'log',
    maxActs: 1,
    cadence: 'recurring',
    cf: 'not quantified',
  },
  {
    id: 'civic-action',
    xpOnly: true,
    cat: 'nature',
    emoji: '📣',
    title: 'Contacted a representative, signed, or showed up',
    unit: 'action',
    presets: [1],
    def: 1,
    cap: 2,
    xp: 25,
    acts: 'log',
    maxActs: 1,
    cadence: 'occasional',
    cf: 'not quantified',
  },
];
