import { BRAND } from '@/lib/brand';
import { JOURNAL_MAX_CHARS, XP_CHALLENGE, XP_JOURNAL_NOTE } from '@/game';

/**
 * Every sentence the Community page prints that is not journal text or editorial content. Plain
 * words, kind, verb first. The page never pretends other people are here.
 */
export const COMMUNITY_COPY = {
  title: 'Community',
  slug: 'Local mode',
  lead: `There are no other people in here yet. This is your journal, a few notes from the ${BRAND.team}, and tools for sharing with friends directly.`,
  localSticker: 'Local mode',

  tabsLabel: 'Community sections',
  tabs: {
    journal: 'Journal',
    share: 'Share card',
    challenge: 'Challenge',
    team: `From the team`,
  },

  composer: {
    title: 'Write a note',
    promptLabel: 'Prompt of the week',
    promptCta: 'Answer it',
    label: 'Your note',
    placeholder: 'Write a note. A win, a wobble, a question, anything.',
    counter: (used: number) => `${used} / ${JOURNAL_MAX_CHARS}`,
    tagsLabel: 'Tag',
    moreTags: 'More tags',
    fewerTags: 'Fewer tags',
    attach: 'Attach today',
    attachHint: 'Adds a line about what you logged today.',
    attachEmpty: 'Nothing logged today yet, so there is nothing to attach.',
    save: 'Save note',
    private: 'Only on this device',
    saved: 'Saved on this device.',
    savedReward: `Saved on this device. +${XP_JOURNAL_NOTE} XP for your first real note today.`,
    empty: 'Write something first.',
  },

  journal: {
    title: 'Your journal',
    lead: 'Notes stay on this device. Nothing here is sent anywhere.',
    privateTag: 'Only on this device',
    searchLabel: (count: number) => `Search ${count} ${count === 1 ? 'note' : 'notes'}`,
    allTags: 'All',
    filterLabel: 'Filter by tag',
    edited: 'Edited',
    edit: 'Edit note',
    delete: 'Delete note',
    cancel: 'Cancel',
    saveEdit: 'Save changes',
    editLabel: 'Edit your note',
    deleteTitle: 'Delete this note?',
    deleteBody: 'It is removed from this device for good. Your XP stays.',
    deleteConfirm: 'Delete note',
    showMore: (count: number) => `Show ${count} more`,
    noMatchTitle: 'No note matches that.',
    noMatchBody: 'Try another word, or clear the tag.',
    clear: 'Clear filters',
    emptySlug: 'Your journal',
    emptyTitle: 'Write your first note',
    emptyBody:
      'A line is enough. Notes are private, kept on this device, and the first one a day pays a little XP.',
    emptyCta: 'Write a note',
  },

  team: {
    title: `From the ${BRAND.team}`,
    lead: 'Eight short starter notes. Written by us, sourced like Learn, and the same for everyone.',
    label: 'Editorial · Starter pack',
    version: (version: string) => `v${version}`,
    save: 'Save',
    saved: 'Saved',
    tryIt: 'Try it',
    openToday: 'Open Today',
    sources: 'Sources',
    showAll: (count: number) => `Show all ${count}`,
    showFewer: 'Show fewer',
    savedOnlyLabel: 'Saved only',
  },

  share: {
    title: 'Share your tree',
    lead: 'A picture of your tree as it is today, made on this device. Your journal and your starting line never go on it.',
    previewLoading: 'Drawing your card…',
    formatLabel: 'Card shape',
    story: 'Story',
    square: 'Square',
    showLabel: 'Show on the card',
    streak: 'Streak',
    kg: '≈ kg CO2e avoided',
    kgHint: 'Estimated from sourced factors, never from AI guesses.',
    week: 'This week’s rings',
    name: 'My name',
    nameHint: 'Off by default. Your tree’s name is always on the card.',
    exportShare: 'Share card',
    exportDownload: 'Download PNG',
    exporting: 'Making the picture…',
    copyCaption: 'Copy caption',
    captionCopied: 'Caption copied.',
    captionFailed: 'Copying did not work. Select the caption and copy it.',
    captionLabel: 'Caption',
    first: 'First share card',
    done: {
      shared: 'Shared. Thanks for spreading the word.',
      'downloaded-png': 'Saved as a PNG.',
      'downloaded-svg':
        'The PNG could not be drawn here, so the card was saved as an SVG picture instead.',
    },
    failed: 'The card could not be saved. Try again, or copy the caption instead.',
    selfReported: 'Self-reported estimates',
    noWorldNote: 'Your browser cannot draw the 3D world, so the card shows an illustrated tree.',
  },

  challenge: {
    title: 'Challenge a friend',
    lead: 'Pick a seven-day dare, make a link and send it. Whoever opens it tracks their own side.',
    noAccounts:
      'No accounts yet, so you each track your own side. Swap result cards when you finish.',
    templateLabel: 'The dare',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Choose a category',
    messageLabel: 'A message (optional)',
    messageHint: (left: number) => `${left} characters left. Plain text only.`,
    messagePlaceholder: 'Loser cooks dinner',
    includeName: 'Put my name in the link',
    includeNameHint: 'Off by default. The link already carries your tree’s name.',
    create: 'Create link',
    busy: 'You already have a challenge running. Finish it or give it up first.',
    needsCategory: 'Choose a category for this one.',
    notOnboarded: 'Plant your tree first, then you can challenge someone.',
    tooLong: 'That message makes the link too long. Shorten it a little.',
    linkLabel: 'Your challenge link',
    copyLink: 'Copy link',
    shareLink: 'Share link',
    linkCopied: 'Link copied.',
    copyFailed: 'Copying did not work. Select the link and copy it.',
    started: 'Your seven days start today.',
    shareText: (dare: string) => `I dare you: ${dare}. Open this link to take it on.`,
    activeTitle: 'Your challenge',
    youStarted: 'You started this one',
    fromFriend: (from: string | null) => (from ? `From ${from}` : 'From a friend'),
    daysLeft: (days: number) => (days === 1 ? 'Last day' : `${days} days left`),
    done: 'Done',
    giveUp: 'Give up',
    giveUpTitle: 'Give up this challenge?',
    giveUpBody: 'There is no penalty. It goes into your history as unfinished.',
    giveUpConfirm: 'Give up',
    keepGoing: 'Keep going',
    finishedTitle: 'You did it.',
    finishedBody: `Seven days, done. The first challenge each week pays ${XP_CHALLENGE} XP, and it earns the Challenger badge.`,
    resultLabel: 'Result link',
    makeResult: 'Make a result link',
    resultHint: 'Send this to whoever dared you, so they can see how it went.',
    resultInclude: 'Put my name on the result',
    historyTitle: 'Past challenges',
    historyLine: (title: string, done: number, of: number) => `${title}: ${done} of ${of}`,
    historySuccess: 'Finished',
    historyOpen: 'Not finished',
    nothingYet: 'No challenge yet. Pick a dare above to start one.',
  },

  invite: {
    featuredSlug: 'You have been dared',
    accept: 'Accept the dare',
    notNow: 'Not now',
    busy: 'You already have a challenge running. Finish it or give it up, then open the link again.',
    giveUpFirst: 'Give up the current one',
    expired: 'This challenge has ended. Start your own?',
    startOwn: 'Start your own',
    damaged: 'This link looks damaged. Ask for a fresh one.',
    resultSlug: 'A result card',
    dismiss: 'Close',
    challengeBack: 'Dare them back',
    messageFrom: 'Their message',
    accepted: 'Challenge accepted.',
    notOnboarded: 'Plant your tree first, then open the link again.',
    runs: 'Your own seven days start the moment you accept.',
  },

  offline: 'You are offline. Everything here still works: notes, cards and links need no network.',
} as const;
