// GENERATED by scripts/build-catalogue.mjs from the evidence base and the product overlay.
// Do not edit by hand: change the inputs and run the script again.

import type { BaselineQuestion, BaselineWorkedExample } from './types';

/** The six questions of the starting-line quiz, verbatim from the evidence base. */
export const BASELINE_QUESTIONS: readonly BaselineQuestion[] = [
  {
    id: 'diet',
    segment: 'food',
    prompt: 'Which best describes how you eat?',
    options: [
      {
        id: 'vegan',
        label: 'Vegan - no animal products',
        note: null,
        tCO2ePerYear: 0.9,
      },
      {
        id: 'vegetarian',
        label: 'Vegetarian - no meat or fish',
        note: 'UK vegetarians in the study ate a lot of cheese; dairy-light vegetarian diets are lower.',
        tCO2ePerYear: 1.52,
      },
      {
        id: 'pescatarian',
        label: 'Pescatarian - fish but no meat',
        note: null,
        tCO2ePerYear: 1.73,
      },
      {
        id: 'low-meat',
        label: 'A little meat - less than 50 g a day (a few times a week)',
        note: null,
        tCO2ePerYear: 1.96,
      },
      {
        id: 'medium-meat',
        label: 'Meat most days - 50 to 99 g a day',
        note: null,
        tCO2ePerYear: 2.57,
      },
      {
        id: 'high-meat',
        label: 'Meat with most meals - 100 g a day or more',
        note: null,
        tCO2ePerYear: 3.74,
      },
    ],
    uncertainty:
      'low/high are the 2.5th-97.5th percentile uncertainty intervals of the study. Values use global-average production footprints (land-use change included) and a 2,000 kcal diet; they run HIGHER than national food-footprint statistics (e.g. the UK average lifestyle food footprint is 1.6 tCO2e in Hot or Cool 2021). Likely overstated for South-Asian vegetarian diets.',
    sources: ['scarborough2023'],
  },
  {
    id: 'transportMode',
    segment: 'transport',
    prompt: 'How do you mostly get around day to day?',
    options: [
      {
        id: 'walk-cycle',
        label: 'Walk or cycle',
        note: null,
        kgCO2ePerKm: 0,
      },
      {
        id: 'ebike',
        label: 'E-bike or e-scooter (own)',
        note: null,
        kgCO2ePerKm: 0.0046,
        kWhPerKm: 0.01,
        gridScaled: true,
      },
      {
        id: 'metro-tram',
        label: 'Metro or tram',
        note: null,
        kgCO2ePerKm: 0.0287,
      },
      {
        id: 'train',
        label: 'Train',
        note: null,
        kgCO2ePerKm: 0.0399,
      },
      {
        id: 'bus',
        label: 'Bus',
        note: null,
        kgCO2ePerKm: 0.128,
      },
      {
        id: 'motorbike',
        label: 'Motorbike or scooter (petrol)',
        note: 'UK average motorbike. India: 100-125 cc scooters and motorcycles emit about 0.032-0.039 kgCO2/km (India GHG Program 2015).',
        kgCO2ePerKm: 0.1432,
        regional: {
          IN: 0.0368,
        },
      },
      {
        id: 'car-shared',
        label: 'Car, usually shared (2 people)',
        note: null,
        kgCO2ePerKm: 0.105,
      },
      {
        id: 'car-electric',
        label: 'Electric car',
        note: null,
        kgCO2ePerKm: 0.0933,
        kWhPerKm: 0.20358,
        gridScaled: true,
      },
      {
        id: 'car-alone',
        label: 'Petrol or diesel car, usually alone',
        note: 'UK average car incl. fuel production. US fleet average 0.244 (tailpipe, EPA); Indian petrol hatchback 0.14 (tailpipe CO2, 2015).',
        kgCO2ePerKm: 0.2099,
        regional: {
          US: 0.2442,
          IN: 0.14,
        },
      },
    ],
    uncertainty:
      'Vehicle size, fuel and occupancy easily move car values by +/-40%. Regional values use different boundaries (UK: CO2e incl. fuel production; US: tailpipe CO2e; India: tailpipe CO2, 2015).',
    sources: ['desnz2026', 'epaEquiv', 'indiaRoad2015', 'mcqueen2019'],
  },
  {
    id: 'weeklyDistance',
    segment: 'transport',
    prompt: 'Roughly how far do you travel in a normal week (all everyday trips)?',
    options: [
      {
        id: 'under-25',
        label: 'Under 25 km',
        note: null,
        kmPerWeek: 15,
      },
      {
        id: '25-75',
        label: '25-75 km',
        note: null,
        kmPerWeek: 50,
      },
      {
        id: '75-150',
        label: '75-150 km',
        note: null,
        kmPerWeek: 110,
      },
      {
        id: '150-300',
        label: '150-300 km',
        note: null,
        kmPerWeek: 220,
      },
      {
        id: '300-500',
        label: '300-500 km',
        note: null,
        kmPerWeek: 400,
      },
      {
        id: 'over-500',
        label: 'Over 500 km',
        note: null,
        kmPerWeek: 650,
      },
    ],
    uncertainty:
      'Band mid-points are ours. For reference, people in England travelled 6082 miles in 2024 by all modes = 188 km a week.',
    sources: ['nts2024'],
  },
  {
    id: 'flights',
    segment: 'flights',
    prompt: 'How much do you fly in a typical year?',
    options: [
      {
        id: 'none',
        label: 'I do not fly',
        note: null,
        tCO2ePerYear: 0,
      },
      {
        id: 'short-1-2',
        label: '1-2 short return flights (under 4 hours each way)',
        note: null,
        tCO2ePerYear: 0.51,
      },
      {
        id: 'short-3-5-or-long-1',
        label: '3-5 short return flights, or 1 long-haul return',
        note: null,
        tCO2ePerYear: 1.53,
      },
      {
        id: 'long-2',
        label: '2 long-haul returns (or 1 long-haul plus several short)',
        note: null,
        tCO2ePerYear: 3.4,
      },
      {
        id: 'long-3-plus',
        label: '3 or more long-haul returns',
        note: null,
        tCO2ePerYear: 5.95,
      },
    ],
    uncertainty:
      'Economy seats; includes fuel production, an 8% routing uplift and a 1.7 multiplier for non-CO2 warming (uncertain - without it values are about 35% lower). Business class is roughly 3x economy on long-haul. Distances are illustrative assumptions. Cross-check: Wynes & Nicholas (2017) give 1.6 tCO2e for one transatlantic return.',
    sources: ['desnz2026', 'desnz2026method', 'wynes2017'],
  },
  {
    id: 'homeEnergy',
    segment: 'home',
    prompt: 'Which sounds most like your home?',
    options: [
      {
        id: 'minimal',
        label: 'Small or shared home, little or no heating or air-conditioning',
        note: null,
        electricityKWh: 380,
        gasKWh: 0,
      },
      {
        id: 'electric-typical',
        label: 'Typical home, all-electric (fans or some AC, electric cooking and hot water)',
        note: null,
        electricityKWh: 1100,
        gasKWh: 0,
      },
      {
        id: 'gas-typical',
        label: 'Typical home with gas (or oil) heating',
        note: null,
        electricityKWh: 1100,
        gasKWh: 4900,
      },
      {
        id: 'gas-high',
        label: 'Large or draughty home with gas or oil heating',
        note: null,
        electricityKWh: 1700,
        gasKWh: 7200,
      },
      {
        id: 'very-high',
        label: 'Large detached home with heavy heating and air-conditioning (North-American style)',
        note: null,
        electricityKWh: 4800,
        gasKWh: 4700,
      },
    ],
    uncertainty:
      "The least certain part of the quiz (+/-60%). Tiers are UK and US benchmarks used as archetypes, not measurements of the user's home; household sizes come from statistics seen only as search excerpts. Excludes building construction and furnishing. Oil and coal heating emit 25-90% more per kWh than gas. Better: let users enter kWh from a bill.",
    sources: [
      'ofgemTDCV',
      'epaEquiv',
      'onsHouseholds',
      'censusHouseholds',
      'desnz2026',
      'ember2026',
    ],
  },
  {
    id: 'shopping',
    segment: 'stuff',
    prompt: 'How much new stuff (clothes, gadgets, furniture, appliances) do you buy?',
    options: [
      {
        id: 'minimal',
        label: 'Very little - I repair, borrow or buy second-hand',
        note: null,
        tCO2ePerYear: 0.1,
      },
      {
        id: 'modest',
        label: 'Only when things wear out',
        note: null,
        tCO2ePerYear: 0.4,
      },
      {
        id: 'regular',
        label: 'Something new most months',
        note: null,
        tCO2ePerYear: 1,
      },
      {
        id: 'frequent',
        label: 'I love shopping - new things most weeks',
        note: null,
        tCO2ePerYear: 2.5,
      },
    ],
    uncertainty:
      'Each tier is pinned to an observed NATIONAL AVERAGE consumer-goods footprint (Hot or Cool 2021, 2019 data). Mapping a shopping habit to a tier is our judgement: +/-50% or more.',
    sources: ['hotOrCool2021'],
  },
];

export const BASELINE_MODEL = {
  version: 1,
  what: 'A rough LIFESTYLE footprint (food, getting around, flights, home energy, stuff) in tonnes of CO2e a year. It is an order-of-magnitude estimate for setting a personal baseline, not a measurement.',
  formula:
    'total = diet + (weeklyKm x 52 x transportMode kgCO2e/km)/1000 + flights + (homeElectricityKWh x grid + homeGasKWh x gasFactor)/1000 + shopping',
  gasKgPerKWh: 0.21252,
  weeksPerYear: 52,
  uncertainty:
    'Treat the total as accurate to about +/-40% for a typical user and worse at the extremes. Always display with "about" and round to one decimal place (or the nearest half tonne).',
  uncertaintyBySegment: {
    food: '+/-30% (study intervals)',
    transport: '+/-40%',
    flights: '-35% to +30% (non-CO2 effects, cabin class, distance)',
    home: '+/-60%',
    stuff: '+/-50% or more',
  },
  notAsked: {
    leisureAndServices:
      'Not asked. Hot or Cool (2021) put leisure + services at 0.1-1.4 tCO2e per person (about 3-16% of lifestyle footprints).',
    publicAndInfrastructure:
      'Not included. About 28% of consumption-based footprints come from government and investment (Hertwich & Peters 2009, as cited by Hot or Cool 2021). Do not compare the quiz result with national per-capita totals without saying so.',
  },
  target2030: {
    tonnes: 2.5,
    range: [2.5, 3.2],
    sources: ['hotOrCool2021'],
  },
  dailyBudgetKg2030: 6.85,
  lifestyleFootprints2019: {
    CA: 13.6,
    FI: 9.7,
    GB: 8.5,
    JP: 8.1,
    CN: 5,
    ZA: 4.9,
    TR: 4.9,
    BR: 3.2,
    IN: 3,
    ID: 2.2,
  },
} as const;

/** Regression examples published with the model; the engine's tests reproduce them. */
export const BASELINE_WORKED_EXAMPLES: readonly BaselineWorkedExample[] = [
  {
    region: 'GB',
    answers: {
      diet: 'medium-meat',
      transportMode: 'car-alone',
      weeklyDistance: '150-300',
      flights: 'short-1-2',
      homeEnergy: 'gas-typical',
      shopping: 'regular',
    },
    result: {
      food: 2.57,
      transport: 2.4,
      flights: 0.51,
      home: 1.28,
      stuff: 1,
      total: 7.8,
    },
  },
  {
    region: 'IN',
    answers: {
      diet: 'vegetarian',
      transportMode: 'motorbike',
      weeklyDistance: '75-150',
      flights: 'none',
      homeEnergy: 'electric-typical',
      shopping: 'modest',
    },
    result: {
      food: 1.52,
      transport: 0.21,
      flights: 0,
      home: 0.74,
      stuff: 0.4,
      total: 2.9,
    },
  },
  {
    region: 'US',
    answers: {
      diet: 'high-meat',
      transportMode: 'car-alone',
      weeklyDistance: '300-500',
      flights: 'short-3-5-or-long-1',
      homeEnergy: 'very-high',
      shopping: 'frequent',
    },
    result: {
      food: 3.74,
      transport: 5.08,
      flights: 1.53,
      home: 2.84,
      stuff: 2.5,
      total: 15.7,
    },
  },
  {
    region: 'WORLD',
    answers: {
      diet: 'vegan',
      transportMode: 'walk-cycle',
      weeklyDistance: 'under-25',
      flights: 'none',
      homeEnergy: 'minimal',
      shopping: 'minimal',
    },
    result: {
      food: 0.9,
      transport: 0,
      flights: 0,
      home: 0.17,
      stuff: 0.1,
      total: 1.2,
    },
  },
];
