// GENERATED by scripts/build-catalogue.mjs from the evidence base and the product overlay.
// Do not edit by hand: change the inputs and run the script again.

import type { EquivalenceDef } from './types';

export const EQUIVALENCE_IDS = [
  'car-km',
  'flight-km',
  'smartphone-charges',
  'kettle-boils',
  'hot-shower-minutes',
  'beef-grams',
  'daily-1p5-budget',
  'world-average-person-day',
] as const;
export type EquivalenceId = (typeof EQUIVALENCE_IDS)[number];

/** Comparisons that make a mass of CO2e imaginable. Always phrased as "roughly the CO2 from". */
export const EQUIVALENCES: readonly (EquivalenceDef & { id: EquivalenceId })[] = [
  {
    id: 'car-km',
    label: 'km driven in an average car',
    kgCO2ePerUnit: 0.2099,
    kWhPerUnit: null,
    gridScaled: false,
    formula: 'kg / 0.2099 (UK 2026 average car, tailpipe 0.16591 + fuel production 0.04399)',
    notes:
      'US fleet average is 0.244 kgCO2e/km tailpipe (EPA: 3.93e-4 t per mile) = 4.1 km per kg.',
    sources: ['desnz2026'],
  },
  {
    id: 'flight-km',
    label: 'km flown (economy, short-haul)',
    kgCO2ePerUnit: 0.1483,
    kWhPerUnit: null,
    gridScaled: false,
    formula: 'kg / 0.1483 (UK 2026 short-haul economy incl. non-CO2 effects and fuel production)',
    notes: 'Per passenger.',
    sources: ['desnz2026'],
  },
  {
    id: 'smartphone-charges',
    label: 'smartphone charges',
    kgCO2ePerUnit: 0.0124,
    kWhPerUnit: 0.019,
    gridScaled: true,
    formula:
      'kg / 0.0124 (EPA: 0.019 kWh per charge x US marginal grid rate). Regional version: kg / (0.019 x grid kg/kWh); world-average grid gives 115 charges per kg.',
    notes:
      'Phone charging is tiny - good for making small numbers feel like something, misleading if it makes phones look like a climate problem.',
    sources: ['epaEquiv', 'ember2026'],
  },
  {
    id: 'kettle-boils',
    label: 'litres of water boiled in a kettle',
    kgCO2ePerUnit: 0.0504,
    kWhPerUnit: 0.1098,
    gridScaled: true,
    formula:
      '1 kg water x 4.186 kJ/kg.K x 85 K (15 -> 100 degC) / 3600 = 0.0988 kWh, / 0.9 kettle efficiency = 0.11 kWh per litre; x grid (world average 0.45849)',
    notes:
      'Physics-based; the 90% efficiency is an assumption. Sanity check: in measured English homes 65% of kettle uses took under 0.1 kWh and 98% under 0.2 kWh (Household Electricity Survey 2012).',
    sources: ['physicsWater', 'hes2012', 'ember2026'],
  },
  {
    id: 'hot-shower-minutes',
    label: 'minutes of hot shower (gas-heated)',
    kgCO2ePerUnit: 0.052,
    kWhPerUnit: null,
    gridScaled: false,
    formula: 'see action "shorter-shower"',
    notes: 'Assumes 7.6 L/min, 25 K temperature rise, 90% efficient gas boiler.',
    sources: ['watersenseShower', 'physicsWater', 'desnz2026'],
  },
  {
    id: 'beef-grams',
    label: 'grams of beef',
    kgCO2ePerUnit: 0.0664,
    kWhPerUnit: null,
    gridScaled: false,
    formula:
      'kg / 0.0664 (mean of beef-herd 99.48 and dairy-herd 33.3 kgCO2e per kg, Poore & Nemecek global means)',
    notes: 'Global means including land-use change; unweighted mean of the two herd types.',
    sources: ['pnFoodKg'],
  },
  {
    id: 'daily-1p5-budget',
    label: 'share of a 1.5 degC-aligned daily lifestyle budget (2030)',
    kgCO2ePerUnit: 6.849,
    kWhPerUnit: null,
    gridScaled: false,
    formula: 'kg / (2.5 t x 1000 / 365) = kg / 6.85; show as a percentage',
    notes:
      'The 2.5 t target is for lifestyle footprints in 2030; it falls to 1.4 t (2040) and 0.7 t (2050).',
    sources: ['hotOrCool2021'],
  },
  {
    id: 'world-average-person-day',
    // Read after "the CO2 from": the label must not say "CO2 emissions" a second time.
    label: "days of the average person's fossil-fuel use",
    kgCO2ePerUnit: 12.96,
    kWhPerUnit: null,
    gridScaled: false,
    formula: 'kg / (4.729 t x 1000 / 365) - world average fossil CO2 per person, 2024',
    notes:
      'Fossil CO2 only. Including methane, nitrous oxide and land use the world average is 6.669 tCO2e per person.',
    sources: ['gcbOwidTerritorial'],
  },
];
