// GENERATED by scripts/build-catalogue.mjs from the evidence base and the product overlay.
// Do not edit by hand: change the inputs and run the script again.

/** Versions and dates of the evidence base these modules were built from. */
export const EVIDENCE_META = {
  factorsVersion: '2026.10',
  generated: '2026-10-06',
  dataRetrieved: '2026-10-06',
  schemaVersion: 1,
  defaultRegion: 'WORLD',
} as const;

/** Building blocks of the regional computation: vehicles, heat, home working, water. */
export const REFERENCE_FACTORS = {
  carKgPerKm: {
    default: 0.2099,
    byRegion: {
      US: 0.2442,
      IN: 0.14,
    },
  },
  busKgPerPassengerKm: {
    default: 0.128,
    byRegion: {
      US: 0.041,
      IN: 0.0152,
    },
  },
  railKgPerPassengerKm: {
    default: 0.0399,
    byRegion: {
      US: 0.0826,
      IN: 0.0078,
    },
  },
  petrolCarKgPerKm: 0.2075,
  electricCarKWhPerKm: 0.20358,
  gasKgPerKWh: 0.21252,
  boilerEfficiency: 0.9,
  heatPumpCop: 3,
  homeworkingKgPerHour: {
    heatingOrCooling: 0.324,
    equipmentOnly: 0.022,
  },
  homeworkingHours: 8,
  waterSupplyKgPerLitre: 0.00036,
  ledKWhPerBulbYear: 26,
  tapOffLitresPerDay: 30,
} as const;
