// GENERATED by scripts/build-catalogue.mjs from the evidence base and the product overlay.
// Do not edit by hand: change the inputs and run the script again.

import type { GroupDef } from './types';

export const GROUP_IDS = [
  'plate',
  'food-rescue',
  'laundry',
  'hot-water',
  'recycling',
  'single-use',
  'flight-swap',
  'secondhand',
  'custom',
] as const;
export type GroupId = (typeof GROUP_IDS)[number];

/** Overlap groups: actions that describe the same real-world thing share a daily cap. */
export const GROUPS: readonly (GroupDef & { id: GroupId })[] = [
  {
    id: 'plate',
    label: 'One tile per meal',
    maxActs: 3,
    hint: 'One tile per meal — pick the best fit.',
    unitCap: null,
    actions: [
      'plant-based-meal',
      'plant-based-instead-of-beef',
      'chicken-instead-of-beef',
      'vegetarian-day',
      'vegan-day',
    ],
  },
  {
    id: 'food-rescue',
    label: 'Same food, one tile',
    maxActs: 2,
    hint: 'Same food, one tile: by weight or by meal.',
    unitCap: null,
    actions: ['food-waste-avoided', 'meal-saved-from-waste'],
  },
  {
    id: 'laundry',
    label: 'One temperature per load',
    maxActs: 2,
    hint: 'One temperature per load.',
    unitCap: 3,
    actions: ['wash-30-instead-of-40', 'wash-cold-instead-of-40'],
  },
  {
    id: 'hot-water',
    label: 'Same water, one tile',
    maxActs: 2,
    hint: 'Same water, one tile.',
    unitCap: null,
    actions: ['shorter-shower', 'hot-water-saved'],
  },
  {
    id: 'recycling',
    label: 'Sorting is one job',
    maxActs: 2,
    hint: 'Recycling a bottle and refusing one are alternatives for the same bottle.',
    unitCap: null,
    actions: [
      'recycle-aluminium-can',
      'recycle-glass-bottle',
      'recycle-plastic-bottle',
      'recycle-paper',
    ],
  },
  {
    id: 'single-use',
    label: 'Small refusals',
    maxActs: 3,
    hint: null,
    unitCap: null,
    actions: ['refuse-single-use-bag', 'refuse-single-use-cup', 'refuse-single-use-bottle'],
  },
  {
    id: 'flight-swap',
    label: 'One tile per trip',
    maxActs: 1,
    hint: "Use the flight's distance, not the rail distance.",
    unitCap: null,
    actions: ['train-instead-of-short-flight-km', 'train-instead-of-short-flight-trip'],
  },
  {
    id: 'secondhand',
    label: 'Second-hand finds',
    maxActs: 2,
    hint: 'Only if it replaced buying new.',
    unitCap: null,
    actions: ['second-hand-tshirt', 'second-hand-jeans'],
  },
  {
    id: 'custom',
    label: 'Custom actions',
    maxActs: 2,
    hint: null,
    unitCap: null,
    actions: [],
  },
];
