/**
 * The evidence-backed catalogue: categories, actions, overlap groups, grid intensity,
 * the baseline quiz model, equivalences and the source registry. Typed, immutable data
 * with no logic. `types.ts` and `categories.ts` are written by hand; every other module
 * is generated by `scripts/build-catalogue.mjs`.
 */
import { ACTIONS, type CatalogueActionId } from './actions';
import { GRID, type RegionId } from './grid';
import { GROUPS, type GroupId } from './groups';
import type { ActionDef, GridRegion, GroupDef } from './types';

export * from './types';
export { CATEGORIES, CATEGORY_BY_ID } from './categories';
export { ACTIONS, ACTION_IDS, type CatalogueActionId } from './actions';
export { GROUPS, GROUP_IDS, type GroupId } from './groups';
export { GRID, REGION_IDS, DEFAULT_REGION, type RegionId } from './grid';
export { EVIDENCE_META, REFERENCE_FACTORS } from './factors';
export { BASELINE_QUESTIONS, BASELINE_MODEL, BASELINE_WORKED_EXAMPLES } from './baseline';
export { EQUIVALENCES, EQUIVALENCE_IDS, type EquivalenceId } from './equivalences';
export { SOURCES } from './sources';

export const ACTION_BY_ID: ReadonlyMap<string, ActionDef & { id: CatalogueActionId }> = new Map(
  ACTIONS.map((action) => [action.id, action]),
);

export const GROUP_BY_ID: ReadonlyMap<string, GroupDef & { id: GroupId }> = new Map(
  GROUPS.map((group) => [group.id, group]),
);

export const GRID_BY_ID: ReadonlyMap<string, GridRegion & { id: RegionId }> = new Map(
  GRID.map((region) => [region.id, region]),
);
