// GENERATED by scripts/build-catalogue.mjs from the evidence base and the product overlay.
// Do not edit by hand: change the inputs and run the script again.

import type { SourceDef } from './types';

/** Every source the catalogue, the baseline model and the equivalences cite, by key. */
export const SOURCES: Readonly<Record<string, SourceDef>> = {
  appleIphone17: {
    title: 'Apple (2025) iPhone 17 Product Environmental Report',
    publisher: 'Apple',
    url: 'https://www.apple.com/environment/pdf/products/iphone/iPhone_17_PER_Sept2025.pdf',
    year: 2025,
    evidence: 'pdf-saved',
  },
  appleMacBookAir: {
    title: 'Apple (2025) MacBook Air (M4) Product Environmental Report',
    publisher: 'Apple',
    url: 'https://www.apple.com/environment/pdf/products/notebooks/M4_MacBook_Air_PER_March2025.pdf',
    year: 2025,
    evidence: 'pdf-saved',
  },
  censusHouseholds: {
    title: 'US Census Bureau QuickFacts - Persons per household, 2020-2024 (2.53)',
    publisher: 'US Census Bureau',
    url: 'https://www.census.gov/quickfacts/fact/table/US/POP715224',
    year: 2025,
    evidence: 'search-excerpt',
  },
  desnz2026: {
    title:
      'UK Government GHG Conversion Factors for Company Reporting 2026 (flat file v1.2, DESNZ)',
    publisher: 'UK Department for Energy Security and Net Zero',
    url: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2026',
    year: 2026,
    evidence: 'raw-file',
  },
  desnz2026method: {
    title:
      '2026 Government greenhouse gas conversion factors for company reporting: Methodology paper',
    publisher: 'UK Department for Energy Security and Net Zero',
    url: 'https://assets.publishing.service.gov.uk/media/6a2940543b15d05a7ce3202e/2026-GHG-conversion-factors-methodology-report.pdf',
    year: 2026,
    evidence: 'pdf-saved',
  },
  doeLED: {
    title: 'US Department of Energy, Energy Saver - LED Lighting',
    publisher: 'US Department of Energy',
    url: 'https://www.energy.gov/energysaver/led-lighting',
    year: 2024,
    evidence: 'search-excerpt',
  },
  doeTree1998: {
    title:
      'Method for Calculating Carbon Sequestration by Trees in Urban and Suburban Settings (Table 2)',
    publisher: 'US Department of Energy, Energy Information Administration',
    url: 'https://www3.epa.gov/climatechange/Downloads/method-calculating-carbon-sequestration-trees-urban-and-suburban-settings.pdf',
    year: 1998,
    evidence: 'pdf-saved',
  },
  ember2026: {
    title: 'Ember Yearly Electricity Data (full release, long format)',
    publisher: 'Ember',
    url: 'https://ember-energy.org/data/yearly-electricity-data/',
    year: 2026,
    evidence: 'raw-file',
  },
  energyStarDryers: {
    title: 'ENERGY STAR Clothes Dryers Key Product Criteria',
    publisher: 'US EPA ENERGY STAR',
    url: 'https://www.energystar.gov/products/clothes_dryers/key_product_criteria',
    year: 2014,
    evidence: 'page-fetched',
  },
  epaEquiv: {
    title:
      'Greenhouse Gas Equivalencies Calculator - Calculations and References (page updated 4 Aug 2026)',
    publisher: 'US Environmental Protection Agency',
    url: 'https://www.epa.gov/energy/greenhouse-gases-equivalencies-calculator-calculations-and-references',
    year: 2026,
    evidence: 'page-saved',
  },
  epaHub2025: {
    title: 'GHG Emission Factors Hub 2025, Table 10 (business travel and employee commuting)',
    publisher: 'US Environmental Protection Agency',
    url: 'https://www.epa.gov/system/files/documents/2025-01/ghg-emission-factors-hub-2025.pdf',
    year: 2025,
    evidence: 'pdf-saved',
  },
  estCalcs: {
    title:
      'Energy Saving Trust - Our calculations: fuel prices and carbon factors (updated 22 Sep 2026)',
    publisher: 'Energy Saving Trust',
    url: 'https://energysavingtrust.org.uk/about-us/our-calculations/',
    year: 2026,
    evidence: 'page-saved',
  },
  estLighting: {
    title: 'Energy Saving Trust - Lighting',
    publisher: 'Energy Saving Trust',
    url: 'https://energysavingtrust.org.uk/advice/lighting/',
    year: 2026,
    evidence: 'page-saved',
  },
  estThermostat: {
    title: 'Energy Saving Trust - Thermostats and heating controls',
    publisher: 'Energy Saving Trust',
    url: 'https://energysavingtrust.org.uk/advice/thermostats-and-heating-controls/',
    year: 2026,
    evidence: 'page-saved',
  },
  estTips: {
    title: 'Energy Saving Trust - Quick tips to save energy (updated 28 Sep 2026)',
    publisher: 'Energy Saving Trust',
    url: 'https://energysavingtrust.org.uk/hub/quick-tips-to-save-energy/',
    year: 2026,
    evidence: 'page-saved',
  },
  estWater: {
    title: 'Energy Saving Trust - Saving water at home',
    publisher: 'Energy Saving Trust',
    url: 'https://energysavingtrust.org.uk/advice/saving-water-at-home/',
    year: 2026,
    evidence: 'page-saved',
  },
  foteinis2020: {
    title:
      'Foteinis, S. (2020) How small daily choices play a huge role in climate change: The disposable paper cup environmental bane. Journal of Cleaner Production 255:120294 (abstract)',
    publisher: 'Journal of Cleaner Production',
    url: 'https://doi.org/10.1016/j.jclepro.2020.120294',
    year: 2020,
    evidence: 'page-fetched',
  },
  gcb2025: {
    title:
      'Friedlingstein et al. (2026) Global Carbon Budget 2025. Earth System Science Data 18:3211-3288',
    publisher: 'Global Carbon Project / ESSD',
    url: 'https://essd.copernicus.org/articles/18/3211/2026/',
    year: 2026,
    evidence: 'page-fetched',
  },
  gcbOwidConsumption: {
    title:
      'Per capita consumption-based CO2 emissions (Global Carbon Budget 2025, processed by Our World in Data)',
    publisher: 'Our World in Data',
    url: 'https://ourworldindata.org/grapher/consumption-co2-per-capita',
    year: 2025,
    evidence: 'raw-file',
  },
  gcbOwidTerritorial: {
    title: 'CO2 emissions per capita (Global Carbon Budget 2025, processed by Our World in Data)',
    publisher: 'Our World in Data',
    url: 'https://ourworldindata.org/grapher/co-emissions-per-capita',
    year: 2025,
    evidence: 'raw-file',
  },
  hes2012: {
    title:
      'Household Electricity Survey: A study of domestic electrical product usage (Intertek report R66141 for DEFRA, DECC and the Energy Saving Trust)',
    publisher: 'UK Government (DEFRA / DECC / Energy Saving Trust)',
    url: 'https://assets.publishing.service.gov.uk/media/5a7c2fd940f0b67d0b11f6df/10043_R66141HouseholdElectricitySurveyFinalReportissue4.pdf',
    year: 2012,
    evidence: 'pdf-saved',
  },
  hollingsworth2019: {
    title:
      'Hollingsworth, Copeland & Johnson (2019) Are e-scooters polluters? The environmental impacts of shared dockless electric scooters. Environ. Res. Lett. 14:084031',
    publisher: 'Environmental Research Letters',
    url: 'https://iopscience.iop.org/article/10.1088/1748-9326/ab2da8',
    year: 2019,
    evidence: 'page-fetched',
  },
  hotOrCool2021: {
    title:
      'Akenji et al. (2021) 1.5-Degree Lifestyles: Towards A Fair Consumption Space for All (Table 3.1, Figures 3.1-3.3)',
    publisher: 'Hot or Cool Institute, Berlin',
    url: 'https://hotorcool.org/1-5-degree-lifestyles-report/',
    year: 2021,
    evidence: 'pdf-saved',
  },
  ieaPlayingMyPart: {
    title:
      'IEA & European Commission (2022) Playing my part: How to save money, reduce reliance on Russian energy, support Ukraine and help the planet',
    publisher: 'International Energy Agency / European Commission',
    url: 'https://www.iea.org/reports/playing-my-part',
    year: 2022,
    evidence: 'page-fetched',
  },
  ieaWFH: {
    title:
      'IEA (2020) Working from home can save energy and reduce emissions. But how much? (commentary)',
    publisher: 'International Energy Agency',
    url: 'https://www.iea.org/commentaries/working-from-home-can-save-energy-and-reduce-emissions-but-how-much',
    year: 2020,
    evidence: 'search-excerpt',
  },
  indiaRail2015: {
    title:
      'India GHG Program (2015) India Specific Rail Transport Emission Factors for Passenger Travel and Material Transport, version 1.0',
    publisher: 'India GHG Program',
    url: 'https://indiaghgp.org/sites/default/files/Rail%20Transport%20Emission.pdf',
    year: 2015,
    evidence: 'pdf-saved',
  },
  indiaRoad2015: {
    title:
      'India GHG Program (2015) India Specific Road Transport Emission Factors, version 1.0 (WRI India, TERI, CII)',
    publisher: 'India GHG Program',
    url: 'https://indiaghgp.org/sites/default/files/Road%20Transport%20Technical%20Paper.pdf',
    year: 2015,
    evidence: 'pdf-saved',
  },
  ipccAR6wg3: {
    title:
      'IPCC (2022) Climate Change 2022: Mitigation of Climate Change. Working Group III, Summary for Policymakers (statements B.3.4, C.10, C.10.2)',
    publisher: 'Intergovernmental Panel on Climate Change',
    url: 'https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_SummaryForPolicymakers.pdf',
    year: 2022,
    evidence: 'pdf-saved',
  },
  jonesOwidGHG: {
    title:
      'Per capita greenhouse gas emissions incl. land use (Jones et al. 2025, processed by Our World in Data)',
    publisher: 'Our World in Data',
    url: 'https://ourworldindata.org/grapher/per-capita-ghg-emissions',
    year: 2025,
    evidence: 'raw-file',
  },
  levis2015: {
    title:
      "Levi Strauss & Co. (2015) The Life Cycle of a Jean: Understanding the environmental impact of a pair of Levi's 501 jeans",
    publisher: 'Levi Strauss & Co.',
    url: 'https://www.levistrauss.com/wp-content/uploads/2015/03/Full-LCA-Results-Deck-FINAL.pdf',
    year: 2015,
    evidence: 'pdf-saved',
  },
  mcqueen2019: {
    title:
      'McQueen, MacArthur & Cherry (2019) The E-Bike Potential: Estimating the Effect of E-Bikes on Person Miles Travelled and Greenhouse Gas Emissions (TREC white paper)',
    publisher: 'Portland State University, Transportation Research and Education Center',
    url: 'https://ppms.trec.pdx.edu/media/project_files/E-bike_Potential_Paper_05_15_19_Final.pdf',
    year: 2019,
    evidence: 'pdf-saved',
  },
  nihPET: {
    title:
      'NIH Environmental Management System - PET water bottle environmental impact (compilation of Benavides et al. 2018, PlasticsEurope 2017, ACC 2011, Franklin Associates 2009, Gironi & Piemonte 2010)',
    publisher: 'US National Institutes of Health',
    url: 'https://nems.nih.gov/sustain/Pages/PETWaterBottleImpact.aspx',
    year: 2019,
    evidence: 'page-fetched',
  },
  nts2024: {
    title:
      'National Travel Survey England 2024: trips by purpose, age, mode and sex (published 27 Aug 2025)',
    publisher: 'UK Department for Transport',
    url: 'https://www.gov.uk/government/statistics/national-travel-survey-2024/nts-2024-trips-by-purpose-age-mode-and-sex',
    year: 2025,
    evidence: 'page-fetched',
  },
  ofgemTDCV: {
    title:
      'Ofgem (2023) Decision on revised Typical Domestic Consumption Values for gas and electricity',
    publisher: 'Ofgem',
    url: 'https://www.ofgem.gov.uk/decision/decision-typical-domestic-consumption-values-2023',
    year: 2023,
    evidence: 'pdf-saved',
  },
  onsHouseholds: {
    title: 'ONS - Families and households in the UK: 2024 (average household size 2.35)',
    publisher: 'UK Office for National Statistics',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/families/bulletins/familiesandhouseholds/2024',
    year: 2025,
    evidence: 'search-excerpt',
  },
  owidFoodLocal: {
    title:
      'Ritchie, H. (2020) You want to reduce the carbon footprint of your food? Focus on what you eat, not whether your food is local',
    publisher: 'Our World in Data',
    url: 'https://ourworldindata.org/food-choice-vs-eating-local',
    year: 2020,
    evidence: 'page-fetched',
  },
  owidFoodMiles: {
    title:
      'Ritchie, H. (2020) Very little of global food is transported by air; this greatly reduces the climate benefits of eating local',
    publisher: 'Our World in Data',
    url: 'https://ourworldindata.org/food-transport-by-mode',
    year: 2020,
    evidence: 'page-fetched',
  },
  petrillo2018: {
    title:
      'Petrillo et al. (2018) Design of a sustainable electric pedal-assisted bike: a life cycle assessment application in Italy (IntechOpen)',
    publisher: 'IntechOpen',
    url: 'https://www.intechopen.com/chapters/64370',
    year: 2018,
    evidence: 'page-fetched',
  },
  physicsWater: {
    title:
      'Specific heat capacity of liquid water, about 4.18 kJ/(kg.K) (NIST Chemistry WebBook, fluid properties of water)',
    publisher: 'US National Institute of Standards and Technology',
    url: 'https://webbook.nist.gov/chemistry/fluid/',
    year: 2023,
    evidence: 'physical-constant',
  },
  pnFoodKg: {
    title:
      "Poore & Nemecek (2018), Reducing food's environmental impacts through producers and consumers (Science 360:987-992) - GHG per kg, via Our World in Data",
    publisher: 'Our World in Data / Science',
    url: 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
    year: 2018,
    evidence: 'raw-file',
  },
  pnFoodProtein: {
    title: 'Poore & Nemecek (2018) - GHG per 100 g protein, via Our World in Data',
    publisher: 'Our World in Data / Science',
    url: 'https://ourworldindata.org/grapher/ghg-per-protein-poore',
    year: 2018,
    evidence: 'raw-file',
  },
  pnMilks: {
    title:
      'Poore & Nemecek (2018) - Environmental footprints of dairy and plant-based milks, via Our World in Data',
    publisher: 'Our World in Data / Science',
    url: 'https://ourworldindata.org/grapher/environmental-footprint-milks',
    year: 2018,
    evidence: 'raw-file',
  },
  pnSupplyChain: {
    title:
      'Poore & Nemecek (2018) - Food: greenhouse gas emissions across the supply chain, via Our World in Data',
    publisher: 'Our World in Data / Science',
    url: 'https://ourworldindata.org/grapher/food-emissions-supply-chain',
    year: 2018,
    evidence: 'raw-file',
  },
  pnnlLighting: {
    title:
      'Gifford et al. (2012) Residential Lighting End-Use Consumption Study: Estimation Framework and Initial Estimates (PNNL-22182)',
    publisher: 'US Department of Energy / Pacific Northwest National Laboratory',
    url: 'https://www1.eere.energy.gov/buildings/publications/pdfs/ssl/2012_residential-lighting-study.pdf',
    year: 2012,
    evidence: 'pdf-saved',
  },
  scarborough2023: {
    title:
      'Scarborough et al. (2023) Vegans, vegetarians, fish-eaters and meat-eaters in the UK show discrepant environmental impacts. Nature Food 4:565-574 (Table 3)',
    publisher: 'Nature Food',
    url: 'https://www.nature.com/articles/s43016-023-00795-w',
    year: 2023,
    evidence: 'page-saved',
  },
  ukEABags: {
    title:
      'Edwards & Fry (2011) Life cycle assessment of supermarket carrier bags: a review of the bags available in 2006 (Report SC030148)',
    publisher: 'Environment Agency (England)',
    url: 'https://www.gov.uk/government/publications/life-cycle-assessment-of-supermarket-carrierbags-a-review-of-the-bags-available-in-2006',
    year: 2011,
    evidence: 'pdf-saved',
  },
  warmOrganics: {
    title:
      'Documentation for the Waste Reduction Model (WARM) v16: Organic Materials (Exhibits 1-10, 1-43, 1-46)',
    publisher: 'US Environmental Protection Agency',
    url: 'https://www.epa.gov/system/files/documents/2023-12/warm_organic_materials_v16_dec.pdf',
    year: 2023,
    evidence: 'pdf-saved',
  },
  warmPackaging: {
    title:
      'Documentation for the Waste Reduction Model (WARM) v16: Containers, Packaging, and Non-Durable Good Materials (Exhibits 1-4, 2-7, 3-7, 5-3)',
    publisher: 'US Environmental Protection Agency',
    url: 'https://www.epa.gov/system/files/documents/2023-12/warm_containers_packaging_and_non-durable_goods_materials_v16_dec.pdf',
    year: 2023,
    evidence: 'pdf-saved',
  },
  watersenseShower: {
    title: 'WaterSense - Showerheads (updated 3 Mar 2026)',
    publisher: 'US Environmental Protection Agency',
    url: 'https://www.epa.gov/watersense/showerheads',
    year: 2026,
    evidence: 'page-fetched',
  },
  watersenseStats: {
    title: 'WaterSense - Statistics and Facts (updated 11 Mar 2026)',
    publisher: 'US Environmental Protection Agency',
    url: 'https://www.epa.gov/watersense/statistics-and-facts',
    year: 2026,
    evidence: 'page-fetched',
  },
  whichWash: {
    title: 'Which? - Washing machine temperature guide (updated 9 Jul 2026)',
    publisher: 'Which?',
    url: 'https://www.which.co.uk/reviews/washing-machines/article/washing-machine-temperature-guide-aLiyf2p96y4d',
    year: 2026,
    evidence: 'page-fetched',
  },
  wrapDisplacement: {
    title:
      'WRAP (2025) Displacement Rates Untangled - press release "Fast fashion could be left on the peg as preloved and repair displace new sales"',
    publisher: 'WRAP',
    url: 'https://www.wrap.ngo/media-centre/press-releases/fast-fashion-could-be-left-peg-preloved-and-repair-displace-new-sales',
    year: 2025,
    evidence: 'page-fetched',
  },
  wrapHHFW2022: {
    title: 'WRAP (2025) Household Food and Drink Waste in the United Kingdom 2022',
    publisher: 'WRAP',
    url: 'https://www.wrap.ngo/resources/report/household-food-and-drink-waste-united-kingdom-2021-22',
    year: 2025,
    evidence: 'pdf-saved',
  },
  wrapMeal: {
    title:
      'WRAP guidance: Expressing redistributed food surplus as meal equivalents (420 g per meal)',
    publisher: 'WRAP',
    url: 'https://wrap.ngo/system/files/2020-09/WRAP-Expressing%20redistributed%20food%20surplus%20as%20meal%20equivalents%20%28WRAP%20guidance%29.pdf',
    year: 2020,
    evidence: 'pdf-saved',
  },
  wynes2017: {
    title:
      'Wynes & Nicholas (2017) The climate mitigation gap: education and government recommendations miss the most effective individual actions. Environ. Res. Lett. 12:074024',
    publisher: 'Environmental Research Letters',
    url: 'https://iopscience.iop.org/article/10.1088/1748-9326/aa7541',
    year: 2017,
    evidence: 'page-fetched',
  },
};
